// Code generated by protoc-gen-go.
// source: log.proto
// DO NOT EDIT!

package rpc

import proto "github.com/golang/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type LogPlayerLoginLogout struct {
	Playerid         *string `protobuf:"bytes,1,req,name=playerid" json:"playerid,omitempty"`
	Time             *int64  `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	Logout           *bool   `protobuf:"varint,3,req,name=logout" json:"logout,omitempty"`
	Ip               *string `protobuf:"bytes,4,req,name=ip" json:"ip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *LogPlayerLoginLogout) Reset()         { *this = LogPlayerLoginLogout{} }
func (this *LogPlayerLoginLogout) String() string { return proto.CompactTextString(this) }
func (*LogPlayerLoginLogout) ProtoMessage()       {}

func (this *LogPlayerLoginLogout) GetPlayerid() string {
	if this != nil && this.Playerid != nil {
		return *this.Playerid
	}
	return ""
}

func (this *LogPlayerLoginLogout) GetTime() int64 {
	if this != nil && this.Time != nil {
		return *this.Time
	}
	return 0
}

func (this *LogPlayerLoginLogout) GetLogout() bool {
	if this != nil && this.Logout != nil {
		return *this.Logout
	}
	return false
}

func (this *LogPlayerLoginLogout) GetIp() string {
	if this != nil && this.Ip != nil {
		return *this.Ip
	}
	return ""
}

func (this *LogPlayerLoginLogout) SetPlayerid(value string) {
	if this != nil {
		this.Playerid = &value
	}
}

func (this *LogPlayerLoginLogout) SetTime(value int64) {
	if this != nil {
		this.Time = &value
	}
}

func (this *LogPlayerLoginLogout) SetLogout(value bool) {
	if this != nil {
		this.Logout = &value
	}
}

func (this *LogPlayerLoginLogout) SetIp(value string) {
	if this != nil {
		this.Ip = &value
	}
}

func init() {
}
