// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Rpc
	Request
	Msg
	SyncError
	RpcErrorResponse
	LoginCnsInfo
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Rpc struct {
	Request          []*Request `protobuf:"bytes,1,rep,name=request" json:"request,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Rpc) Reset()                    { *m = Rpc{} }
func (m *Rpc) String() string            { return proto.CompactTextString(m) }
func (*Rpc) ProtoMessage()               {}
func (*Rpc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Rpc) GetRequest() []*Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type Request struct {
	Method            *string `protobuf:"bytes,1,req,name=method" json:"method,omitempty"`
	SerializedRequest []byte  `protobuf:"bytes,2,opt,name=serialized_request,json=serializedRequest" json:"serialized_request,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Request) GetSerializedRequest() []byte {
	if m != nil {
		return m.SerializedRequest
	}
	return nil
}

type Msg struct {
	Code             *string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Text             *string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Msg) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *Msg) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type SyncError struct {
	Text             *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncError) Reset()                    { *m = SyncError{} }
func (m *SyncError) String() string            { return proto.CompactTextString(m) }
func (*SyncError) ProtoMessage()               {}
func (*SyncError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SyncError) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type RpcErrorResponse struct {
	Method           *string `protobuf:"bytes,1,req,name=method" json:"method,omitempty"`
	Text             *string `protobuf:"bytes,2,req,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpcErrorResponse) Reset()                    { *m = RpcErrorResponse{} }
func (m *RpcErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*RpcErrorResponse) ProtoMessage()               {}
func (*RpcErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RpcErrorResponse) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *RpcErrorResponse) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type LoginCnsInfo struct {
	CnsIp            *string `protobuf:"bytes,1,req,name=cnsIp" json:"cnsIp,omitempty"`
	GsInfo           *string `protobuf:"bytes,2,req,name=gsInfo" json:"gsInfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginCnsInfo) Reset()                    { *m = LoginCnsInfo{} }
func (m *LoginCnsInfo) String() string            { return proto.CompactTextString(m) }
func (*LoginCnsInfo) ProtoMessage()               {}
func (*LoginCnsInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginCnsInfo) GetCnsIp() string {
	if m != nil && m.CnsIp != nil {
		return *m.CnsIp
	}
	return ""
}

func (m *LoginCnsInfo) GetGsInfo() string {
	if m != nil && m.GsInfo != nil {
		return *m.GsInfo
	}
	return ""
}

func init() {
	proto.RegisterType((*Rpc)(nil), "rpc.Rpc")
	proto.RegisterType((*Request)(nil), "rpc.Request")
	proto.RegisterType((*Msg)(nil), "rpc.Msg")
	proto.RegisterType((*SyncError)(nil), "rpc.SyncError")
	proto.RegisterType((*RpcErrorResponse)(nil), "rpc.RpcErrorResponse")
	proto.RegisterType((*LoginCnsInfo)(nil), "rpc.LoginCnsInfo")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8e, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0xd9, 0x44, 0x3d, 0x76, 0x4c, 0xa1, 0x8b, 0x48, 0x3a, 0x43, 0x0a, 0x49, 0x73, 0x29,
	0xac, 0xc5, 0x46, 0x2c, 0x0e, 0x14, 0x64, 0xfc, 0x01, 0x22, 0x9b, 0x31, 0x06, 0xbc, 0xdd, 0x75,
	0x26, 0x82, 0xfa, 0xeb, 0x25, 0xd9, 0xbd, 0x8b, 0x8d, 0xdd, 0xbc, 0xf7, 0xe6, 0x7b, 0x33, 0xa0,
	0xb7, 0xd2, 0xb7, 0x81, 0xfd, 0xe8, 0x4d, 0xce, 0xc1, 0xd6, 0x6b, 0xc8, 0x31, 0x58, 0x73, 0x09,
	0x2b, 0xa6, 0x8f, 0x4f, 0x92, 0xb1, 0x54, 0x55, 0xde, 0x1c, 0x5f, 0x15, 0x2d, 0x07, 0xdb, 0x62,
	0xf4, 0x70, 0x17, 0xd6, 0x8f, 0xb0, 0x4a, 0x9e, 0x39, 0x87, 0xa3, 0x2d, 0x8d, 0x6f, 0xbe, 0x2b,
	0x55, 0x95, 0x35, 0x1a, 0x93, 0x32, 0x6b, 0x30, 0x42, 0x3c, 0xbc, 0xbc, 0x0f, 0x3f, 0xd4, 0x3d,
	0xef, 0x5a, 0xb3, 0x4a, 0x35, 0x05, 0x9e, 0x2e, 0x49, 0xaa, 0x99, 0x1e, 0x78, 0x90, 0xde, 0x18,
	0x38, 0xb0, 0xbe, 0xa3, 0x52, 0x55, 0xaa, 0xd1, 0x38, 0xcf, 0x93, 0x37, 0xd2, 0x57, 0x64, 0x35,
	0xce, 0x73, 0x7d, 0x01, 0xfa, 0xe9, 0xdb, 0xd9, 0x3b, 0x66, 0xcf, 0xfb, 0x05, 0xf5, 0x67, 0xe1,
	0x06, 0x4e, 0x30, 0xc4, 0x1c, 0x49, 0x82, 0x77, 0x42, 0xff, 0xbe, 0xba, 0x1c, 0xc8, 0xf6, 0xfc,
	0x35, 0x14, 0xf7, 0xbe, 0x1f, 0xdc, 0xad, 0x93, 0x8d, 0x7b, 0xf5, 0xe6, 0x0c, 0x0e, 0xad, 0x93,
	0x4d, 0x48, 0x68, 0x14, 0x53, 0x63, 0x3f, 0xe7, 0x89, 0x4d, 0xea, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x1f, 0x55, 0x3c, 0x85, 0x5f, 0x01, 0x00, 0x00,
}
